#lang racket/base
(require ffi/unsafe)

(provide
 (rename-out
   ;; ── C 类型 ──
   [_int 类型-整数]
   [_uint 类型-无符号整数]
   [_long 类型-长整数]
   [_ulong 类型-无符号长整数]
   [_short 类型-短整数]
   [_ushort 类型-无符号短整数]
   [_sint 类型-有符号整数]
   [_sshort 类型-有符号短整数]
   [_slong 类型-有符号长整数]
   [_sbyte 类型-有符号字节]
   [_byte 类型-字节]
   [_ubyte 类型-无符号字节]
   [_word 类型-字]
   [_uword 类型-无符号字]
   [_sword 类型-有符号字]
   [_fixnum 类型-定点数]
   [_ufixnum 类型-无符号定点数]
   [_fixint 类型-定点整数]
   [_ufixint 类型-无符号定点整数]
   [_intptr 类型-整数指针]
   [_uintptr 类型-无符号整数指针]
   [_sintptr 类型-有符号整数指针]
   [_intmax 类型-最大整数]
   [_uintmax 类型-无符号最大整数]
   [_size 类型-大小]
   [_ssize 类型-有符号大小]
   [_ptrdiff 类型-指针差]
   [_float 类型-单精度浮点]
   [_double 类型-双精度浮点]
   [_longdouble 类型-长双精度浮点]
   [_bool 类型-布尔]
   [_stdbool 类型-标准布尔]
   [_string 类型-字符串]
   [_path 类型-路径]
   [_symbol 类型-符号]
   [_bytes 类型-字节串]
   [_void 类型-空]
   [_pointer 类型-指针]
   [_gcpointer 类型-GC指针]
   [_cpointer 类型-C指针]
   [_fpointer 类型-函数指针]
   [_racket 类型-Racket]
   [_scheme 类型-Scheme]
   [_enum 类型-枚举]
   [_bitmask 类型-位掩码]
   [_file 类型-文件]
   [_fun 类型-函数]
   [_cprocedure 类型-C过程]
   [_ptr 类型-指针别名]
   [_box 类型-盒]
   [_list 类型-列表]
   [_vector 类型-向量]
   [_gcable 类型-可GC]
   [_or-null 类型-或空]
   [_array 类型-数组]
   [_list-struct 类型-列表结构]
   [_llong 类型-长长整数]
   [_ullong 类型-无符号长长整数]
   [_sllong 类型-有符号长长整数]
   [_wchar 类型-宽字符]
   [default-_string-type 默认-字符串类型]

   ;; ── ctype 操作 ──
   [ctype? 类型?]
   [ctype-sizeof 类型-尺寸]
   [ctype-alignof 类型-对齐]
   [compiler-sizeof 编译器-大小]
   [make-ctype 制造类型]
   [make-array-type 制造数组类型]
   [make-cstruct-type 制造C结构类型]
   [make-union-type 制造联合类型]
   [make-sized-byte-string 制造定长字节串]

   ;; ── 内存 ──
   [malloc 分配内存]
   [free 释放内存]
   [malloc-immobile-cell 分配固定单元]
   [free-immobile-cell 释放固定单元]
   [memcpy 内存复制]
   [memmove 内存移动]
   [memset 内存设置]
   [register-finalizer 注册终结器]
   [end-stubborn-change 结束顽固变更]

   ;; ── 指针 ──
   [ptr-ref 指针-引用]
   [ptr-set! 指针-设置!]
   [ptr-add 指针-加]
   [ptr-add! 指针-加!]
   [ptr-offset 指针-偏移]
   [ptr-equal? 指针-相等?]
   [set-ptr-offset! 设置指针偏移!]
   [cpointer? C指针?]
   [cpointer-tag C指针-标签]
   [cpointer-has-tag? C指针-有标签?]
   [cpointer-push-tag! C指针-推标签!]
   [cpointer-gcable? C指针-可GC?]
   [set-cpointer-tag! 设置C指针标签!]
   [cpointer-predicate-procedure? C指针谓词过程?]
   [offset-ptr? 偏移指针?]

   ;; ── 数组 ──
   [array? 数组?]
   [array-type 数组-类型]
   [array-length 数组-长度]
   [array-ptr 数组-指针]
   [array-ref 数组-引用]
   [array-set! 数组-设置!]
   [in-array 在数组]
   [compute-offsets 计算偏移]

   ;; ── 联合 ──
   [union? 联合?]
   [union-ptr 联合-指针]
   [union-ref 联合-引用]
   [union-set! 联合-设置!]

   ;; ── FFI 库 ──
   [ffi-lib FFI库]
   [ffi-lib? FFI库?]
   [ffi-lib-name FFI库-名称]
   [get-ffi-obj 获取FFI对象]
   [ffi-obj-ref FFI对象-引用]
   [set-ffi-obj! 设置FFI对象!]
   [lookup-errno 查找错误号]
   [saved-errno 保存错误号]

   ;; ── 函数 ──
   [function-ptr 函数-指针]
   [define-c 定义C]
   [define-cstruct 定义C结构]
   [define-cpointer-type 定义C指针类型]
   [define-fun-syntax 定义函数语法]
   [make-c-parameter 制造C参数]
   [cast 强制转换]

   ;; ── 其他 ──
   [make-late-weak-box 制造延迟弱盒]
   [make-late-weak-hasheq 制造延迟弱哈希]
   [void 空]))
