#lang racket/base

(require (for-syntax racket/base)
         racket/dict
         racket/file
         racket/list
         racket/string)

;; ============================================================
;; racket-cn/translator — 中文 Racket ↔ 英文 Racket 翻译器
;; ============================================================

(provide
  翻译文件
  翻译语法
  翻译字符串
  英->中
  中->英
  标识符-翻译表)

;; ============================================================
;; 1. 翻译映射表 (英文 . 中文)
;; ============================================================
(define 标识符-翻译表
  '(
    ;; 模块系统
    (require                   . 引用)
    (provide                   . 提供)
    (all-defined-out           . 全定义导出)
    ;; 核心特殊形式
    (define                    . 定义)
    (define-syntax             . 定义语法)
    (define-syntax-rule        . 定义语法规则)
    (define-values             . 定义多值)
    (lambda                    . 函数)
    (case-lambda               . 分支函数)
    (if                        . 如果)
    (cond                      . 条件)
    (else                      . 否则)
    (case                      . 分支)
    (let                       . 令)
    (let*                      . 依次令)
    (letrec                    . 递归令)
    (let-values                . 令多值)
    (let*-values               . 依次令多值)
    (letrec-values             . 递归令多值)
    (set!                      . 赋值！)
    (begin                     . 顺序求值)
    (begin0                    . 顺序求值返回首个值)
    (when                      . 当)
    (unless                    . 除非)
    (and                       . 且)
    (or                        . 或)
    (not                       . 非)
    (quote                     . 引述)
    (quasiquote                . 准引用)
    (unquote                   . 反引用)
    (quasisyntax               . 准语法)
    (unsyntax                  . 反语法)
    (syntax                    . 语法)
    (syntax-case               . 语法匹配)
    (syntax-rules              . 语法规则)
    (with-syntax               . 带语法)
    ;; 续延与控制
    (call/cc                                         . 续延)
    (call-with-current-continuation                  . 调用-当前续延)
    (call-with-composable-continuation               . 调用-可组合续延)
    (call-with-escape-continuation                   . 调用-逃逸续延)
    (call-with-continuation-prompt                   . 调用-续延提示)
    (call-with-values                                . 调用-多值)
    (dynamic-wind                                    . 动态-包裹)
    (raise                                           . 引发)
    (error                                           . 错误)
    (with-handlers                                   . 处理异常)
    ;; 布尔
    (boolean?                                        . 布尔?)
    ;; 对与列表
    (cons                   . 对)
    (car                    . 首)
    (cdr                    . 尾)
    (pair?                  . 对?)
    (null                   . 空值)
    (null?                  . 空值?)
    (list                   . 列表)
    (list?                  . 列表?)
    (list*                  . 列表*)
    (length                 . 长度)
    (append                 . 拼接)
    (reverse                . 反转)
    (member                 . 成员)
    (assoc                  . 关联查找)
    (caar                   . 首首)
    (cadr                   . 第二)
    (cdar                   . 尾首)
    (cddr                   . 尾尾)
    ;; 映射与折叠
    (map                    . 映射)
    (andmap                 . 全映射)
    (ormap                  . 有映射)
    (filter                 . 过滤)
    (foldl                  . 左折叠)
    (foldr                  . 右折叠)
    (for-each               . 遍历)
    (apply                  . 应用)
    (compose                . 函数组合)
    (compose1               . 函数组合1)
    (values                 . 多值)
    ;; 数学
    (+                      . +)
    (abs                    . 绝对值)
    (add1                   . 加1)
    (sub1                   . 减1)
    (expt                   . 幂)
    (sqrt                   . 平方根)
    (sin                    . 正弦)
    (cos                    . 余弦)
    (tan                    . 正切)
    (floor                  . 向下取整)
    (ceiling                . 向上取整)
    (round                  . 四舍五入)
    (max                    . 最大值)
    (min                    . 最小值)
    (modulo                 . 取模)
    (quotient               . 整除商)
    (remainder              . 余数)
    (even?                  . 偶数?)
    (odd?                   . 奇数?)
    (zero?                  . 零?)
    (positive?              . 正?)
    (negative?              . 负?)
    (number?                . 数字?)
    (complex?               . 复数?)
    (real?                  . 实数?)
    (integer?               . 整数?)
    (random                 . 随机)
    ;; 比较
    (eq?                    . 等同?)
    (eqv?                   . 等价?)
    (equal?                 . 等值?)
    ;; 字符串
    (string?                . 字符串?)
    (string                 . 字符串)
    (string-append          . 字符串-拼接)
    (string-length          . 字符串-长度)
    (string-ref             . 字符串-引用)
    (substring              . 子字符串)
    (string->number         . 字符串->数字)
    (number->string         . 数字->字符串)
    (string->symbol         . 字符串->符号)
    (symbol->string         . 符号->字符串)
    (string->list           . 字符串->列表)
    (list->string           . 列表->字符串)
    (string=?               . 字符串=?)
    (string<?               . 字符串<?)
    (string>?               . 字符串>?)
    (string-ci=?            . 字符串忽略大小写=?)
    (string-downcase        . 字符串-小写)
    (string-upcase          . 字符串-大写)
    (string-titlecase       . 字符串-首字母大写)
    (format                 . 格式化)
    ;; 字符
    (char?                  . 字符?)
    (char->integer          . 字符->整数)
    (integer->char          . 整数->字符)
    (char=?                 . 字符=?)
    (char-alphabetic?       . 字符-字母?)
    (char-numeric?          . 字符-数字?)
    (char-whitespace?       . 字符-空白?)
    (char-upcase            . 字符-大写)
    (char-downcase          . 字符-小写)
    ;; 符号
    (symbol?                . 符号?)
    (gensym                 . 生成唯一符号)
    (generate-temporaries   . 生成临时标识符)
    ;; 关键字
    (keyword?               . 关键字?)
    (keyword->string        . 关键字->字符串)
    (string->keyword        . 字符串->关键字)
    ;; 向量
    (vector                 . 向量)
    (vector?                . 向量?)
    (vector-ref             . 向量-引用)
    (vector-set!            . 向量-赋值！)
    (vector-length          . 向量-长度)
    (make-vector            . 制造向量)
    (vector->list           . 向量->列表)
    (list->vector           . 列表->向量)
    (vector-fill!           . 向量-填充！)
    ;; 字节串
    (bytes                  . 字节串)
    (bytes?                 . 字节串?)
    (bytes-ref              . 字节串-引用)
    (bytes-length           . 字节串-长度)
    (make-bytes             . 制造字节串)
    (bytes-append           . 字节串-拼接)
    (bytes-copy             . 字节串-复制)
    ;; 哈希表
    (hash                   . 哈希)
    (hash?                  . 哈希?)
    (hash-ref               . 哈希-引用)
    (hash-set               . 哈希-设置)
    (hash-remove            . 哈希-移除)
    (hash-count             . 哈希-计数)
    (hash-keys              . 哈希-键)
    (hash-values            . 哈希-值)
    (hash->list             . 哈希->列表)
    (hash-copy              . 哈希-复制)
    (make-hash              . 制造哈希)
    (hasheq                 . 哈希等同)
    (hasheqv                . 哈希等价)
    ;; 盒
    (box                    . 盒)
    (box?                   . 盒?)
    (unbox                  . 开盒)
    (set-box!               . 盒赋值！)
    (box-immutable          . 不可变盒)
    ;; 参数
    (make-parameter         . 制造参数)
    (parameterize           . 参数化)
    (current-input-port     . 当前输入端口)
    (current-output-port    . 当前输出端口)
    (current-error-port     . 当前错误端口)
    (current-directory      . 当前目录)
    ;; 输入输出
    (display                . 显示)
    (displayln              . 显示行)
    (print                  . 打印)
    (println                . 打印行)
    (write                  . 写出)
    (printf                 . 格式化输出)
    (read                   . 读取)
    (read-line              . 读取-行)
    (read-string            . 读取-字符串)
    (read-bytes             . 读取-字节串)
    (read-char              . 读取-字符)
    (peek-char              . 窥视-字符)
    (newline                . 换行)
    (open-input-string      . 打开输入字符串)
    (open-output-string     . 打开输出字符串)
    (close-input-port       . 关闭输入端口)
    (close-output-port      . 关闭输出端口)
    (port?                  . 端口?)
    (input-port?            . 输入端口?)
    (output-port?           . 输出端口?)
    (eof                    . 文件尾)
    (eof-object?            . 文件尾?)
    ;; 文件系统
    (file-exists?           . 文件存在?)
    (directory-exists?      . 目录存在?)
    (delete-file            . 删除文件)
    (make-directory         . 创建目录)
    (copy-file              . 复制文件)
    (path?                  . 路径?)
    (path->string           . 路径->字符串)
    (find-system-path       . 查找系统路径)
    (build-path             . 构建路径)
    (raise-argument-error   . 引发参数错误)
    (raise-syntax-error     . 引发语法错误)
    ;; 线程
    (thread                 . 线程)
    (thread?                . 线程?)
    (sleep                  . 睡眠)
    (kill-thread            . 终止线程)
    (current-thread         . 当前线程)
    (break-thread           . 中断线程)
    (make-semaphore         . 制造信号量)
    (semaphore-post         . 信号量-发送)
    (semaphore-wait         . 信号量-等待)
    ;; 结构
    (struct                 . 结构)
    (struct?                . 结构?)
    ;; 异常
    (exn                    . 异常)
    (exn?                   . 异常?)
    ;; 宏/语法
    (identifier?            . 标识符?)
    (syntax->datum          . 语法->数据)
    (datum->syntax          . 数据->语法)
    (begin-for-syntax       . 编译期开始)
    (define-for-syntax      . 编译期定义)
    (syntax-e               . 语法值)
    (syntax->list           . 语法->列表)
    (syntax-source          . 语法-源)
    (syntax-line            . 语法-行)
    (syntax-column          . 语法-列)
    (syntax-position        . 语法-位置)
    (free-identifier=?      . 自由标识符等同?)
    (bound-identifier=?     . 绑定标识符等同?)
    (identifier-binding     . 标识符绑定)
    (let-syntax             . 令语法)
    (letrec-syntax          . 递归令语法)
    (let-syntaxes           . 令语法多)
    (letrec-syntaxes        . 递归令语法多)
    (local-expand           . 局部展开)
    (make-rename-transformer . 制造重名转换器)
    ;; 迭代/循环
    (for                    . 循环)
    (for*                   . 循环*)
    (for/list               . 循环/列表)
    (for*/list              . 循环*/列表)
    (for/vector             . 循环/向量)
    (for*/vector            . 循环*/向量)
    (for/and                . 循环/且)
    (for*/and               . 循环*/且)
    (for/or                 . 循环/或)
    (for*/or                . 循环*/或)
    (for/first              . 循环/首个)
    (for*/first             . 循环*/首个)
    (for/last               . 循环/末个)
    (for*/last              . 循环*/末个)
    (for/fold               . 循环/折叠)
    (for*/fold              . 循环*/折叠)
    (in-range               . 在范围)
    (in-list                . 在列表)
    (in-vector              . 在向量)
    (in-string              . 在字符串)
    (in-bytes               . 在字节串)
    (in-hash                . 在哈希)
    (in-naturals            . 在自然数)
    (in-port                . 在端口)
    ;; 命名空间
    (dynamic-require         . 动态引用)
    (current-namespace       . 当前命名空间)
    (make-base-namespace     . 制造基础命名空间)
    (namespace-variable-value . 命名空间-变量值)
    ;; 系统
    (exit                   . 退出)
    (collect-garbage        . 垃圾回收)
    (version                . 版本)
    (current-milliseconds   . 当前毫秒)
    (current-seconds        . 当前秒)
    ;; 类型谓词
    (void                   . 空)
    (void?                  . 空?)
    ;; racket 特有 (main-impl.rkt)
    (delay                  . 延迟)
    (force                  . 求值)
    (promise?               . 承诺?)
    (command-line           . 命令行)
    ;; racket/hash
    (hash-union             . 哈希-并集)
    (hash-intersect         . 哈希-交集)
    (hash-keys-subset?      . 哈希-键子集?)
    (hash-empty?            . 哈希-空?)
    (hash-map               . 哈希-映射)
    (hash-for-each          . 哈希-遍历)
    (hash-filter            . 哈希-过滤)
    (hash-filter-keys       . 哈希-过滤键)
    (hash-filter-values     . 哈希-过滤值)
    ;; racket/vector
    (vector-append          . 向量-拼接)
    (vector-copy            . 向量-复制)
    (vector-copy!           . 向量-复制!)
    (vector-map             . 向量-映射)
    (vector-map!            . 向量-映射!)
    (vector-filter          . 向量-过滤)
    (vector-filter-not      . 向量-过滤取反)
    (vector-count           . 向量-计数)
    (vector-member          . 向量-成员)
    (vector-memq            . 向量-成员等同)
    (vector-memv            . 向量-成员等价)
    (vector-argmin          . 向量-最小参数)
    (vector-argmax          . 向量-最大参数)
    (vector-immutable       . 向量-不可变)
    (vector-empty?          . 向量-空?)
    (vector-take            . 向量-取前)
    (vector-drop            . 向量-去掉前)
    (vector-split-at        . 向量-切分)
    (vector-take-right      . 向量-取后)
    (vector-drop-right      . 向量-去掉后)
    (vector-split-at-right  . 向量-右切分)
    (vector-sort            . 向量-排序)
    (vector-sort!           . 向量-排序!)
    ;; racket/list
    (take                   . 取前)
    (drop                   . 去掉前)
    (split-at               . 切分)
    (take-right             . 取后)
    (drop-right             . 去掉后)
    (split-at-right         . 从右切分)
    (append-map             . 拼接映射)
    (filter-map             . 过滤映射)
    (count                  . 计数)
    (argmin                 . 最小参数)
    (argmax                 . 最大参数)
    (group-by               . 分组)
    (remove                 . 移除)
    (remq                   . 移除等同)
    (remv                   . 移除等价)
    (remove*                . 多移除)
    (sort                   . 排序)
    (flatten                . 展平)
    (first                  . 第一个)
    (second                 . 第二个)
    (third                  . 第三个)
    (fourth                 . 第四个)
    (fifth                  . 第五个)
    (rest                   . 剩余)
    (last                   . 最后一个)
    (cons?                  . 有对?)
    (make-list              . 制造列表)
    (range                  . 范围)
    ;; racket/string
    (string-contains?       . 字符串-包含?)
    (string-prefix?         . 字符串-前缀?)
    (string-suffix?         . 字符串-后缀?)
    (non-empty-string?      . 非空字符串?)
    ;; racket/sequence
    (sequence-length        . 序列-长度)
    (sequence-ref           . 序列-引用)
    (sequence-tail          . 序列-尾部)
    (sequence-map           . 序列-映射)
    (sequence-append        . 序列-拼接)
    (sequence-filter        . 序列-过滤)
    (sequence-add-between   . 序列-加分隔)
    (sequence?              . 序列?)
    (sequence->list         . 序列->列表)
    ;; racket/match
    (match                  . 匹配)
    (match*                 . 多匹配)
    (match-lambda           . 匹配函数)
    (match-lambda*          . 匹配多函数)
    (match-let              . 匹配令)
    (match-let*             . 依次匹配令)
    (match-let-values       . 匹配令多值)
    (match-define           . 匹配定义)
    ;; racket/class
    (class                  . 类)
    (class*                 . 类*)
    (new                    . 新建)
    (send                   . 发送)
    (send*                  . 多发送)
    (define/public          . 定义/公开)
    (define/private         . 定义/私有)
    (define/override        . 定义/覆写)
    (field                  . 字段)
    (init-field             . 初始字段)
    (inherit                . 继承)
    (super                  . 父类)
    (this                   . 自身)
    ;; racket/dict
    (dict?                  . 字典?)
    (dict-ref               . 字典-引用)
    (dict-set               . 字典-设置)
    (dict-remove            . 字典-移除)
    (dict-keys              . 字典-键)
    (dict-values            . 字典-值)
    (dict-count             . 字典-计数)
    (dict->list             . 字典->列表)
    (dict-copy              . 字典-复制)
    (dict-map               . 字典-映射)
    ;; racket/set
    (set                    . 集合)
    (set?                   . 集合?)
    (set-add                . 集合-添加)
    (set-remove             . 集合-移除)
    (set-count              . 集合-计数)
    (set-member?            . 集合-成员?)
    (set-union              . 集合-并集)
    (set-intersect          . 集合-交集)
    (set-subtract           . 集合-差集)
    (list->set              . 列表->集合)
    (set->list              . 集合->列表)
    (set-copy               . 集合-复制)
    (set-map                . 集合-映射)
    ;; racket/stream
    (stream                 . 流)
    (stream?                . 流?)
    (stream-cons            . 流-对)
    (stream-first           . 流-首个)
    (stream-rest            . 流-剩余)
    (stream-ref             . 流-引用)
    (stream->list           . 流->列表)
    (in-stream              . 在流)
    (stream-map             . 流-映射)
    (stream-filter          . 流-过滤)
    (stream-fold            . 流-折叠)
    ;; racket/function
    (curry                  . 柯里化)
    (curryr                 . 右柯里化)
    (const                  . 常量)
    (identity               . 恒等)
    (thunk                  . 零参函数)
    (negate                 . 取反)
    ;; racket/future
    (future                 . 未来)
    (touch                  . 触碰)
    (future?                . 未来?)
    ;; racket/generator
    (generator              . 生成器)
    (generator-state        . 生成器-状态)
    (in-generator           . 在生成器中)
    (infinite-generator     . 无限生成器)
    (sequence->generator    . 序列->生成器)
    ;; racket/date
    (date?                  . 日期?)
    (date->string           . 日期->字符串)
    (seconds->date          . 秒->日期)
    (date->seconds          . 日期->秒)
    (date-display-format    . 日期-显示格式)
    (find-seconds           . 查找秒)
    (date*                  . 日期*)
    (current-date           . 当前日期)
    ;; racket/random
    (random-seed            . 随机-种子)
    (crypto-random-bytes    . 加密随机字节)
    ;; racket/system
    (system                 . 系统-执行)
    (system*                . 系统-执行*)
    (system/exit-code       . 系统-执行/退出码)
    (system-type            . 系统-类型)
    ;; racket/pretty
    (pretty-print           . 美化-打印)
    (pretty-write           . 美化-写出)
    (pretty-display         . 美化-显示)
    (pretty-format          . 美化-格式化)
    (pretty-printing        . 美化-打印?)
    (pretty-print-columns   . 美化-打印-列数)
    (pretty-print-depth     . 美化-打印-深度)
    ;; racket/contract
    (contract               . 合约)
    (contract-out           . 合约导出)
    (define/contract        . 定义/合约)
    (any/c                  . 任意/合约)
    (list/c                 . 列表/合约)
    (vector/c               . 向量/合约)
    (integer-in             . 整数范围)
    (real-in                . 实数范围)
    (between/c              . 区间/合约)
    (or/c                   . 或/合约)
    (and/c                  . 且/合约)
    (not/c                  . 非/合约)
    ;; racket/file
    (file->string           . 文件->字符串)
    (file->bytes            . 文件->字节串)
    (file->lines            . 文件->行)
    (file->list             . 文件->列表)
    (file->value            . 文件->值)
    (file->bytes-lines      . 文件->字节行)
    (find-files             . 查找文件)
    (make-temporary-file    . 制造临时文件)
    (write-to-file          . 写入到文件)
    (display-to-file        . 显示-到-文件)
    ;; racket/path
    (normalize-path              . 规范化路径)
    (resolve-path                . 解析路径)
    (absolute-path?              . 绝对路径?)
    (relative-path?              . 相对路径?)
    (path-only                   . 路径-仅目录)
    (path-replace-extension      . 路径-替换扩展名)
    (path-add-extension          . 路径-添加扩展名)
    (path-replace-suffix         . 路径-替换后缀)
    (path-add-suffix             . 路径-添加后缀)
    (split-path                  . 拆分路径)
    (explode-path                . 分解路径)
    (simplify-path               . 简化路径)
    (cleanse-path                . 清洗路径)
    (current-directory-for-user  . 当前目录-用户)
    ;; racket/port
    (call-with-input-string     . 调用-输入字符串)
    (call-with-output-string    . 调用-输出字符串)
    (call-with-input-bytes      . 调用-输入字节串)
    (call-with-output-bytes     . 调用-输出字节串)
    (copy-port                  . 复制端口)
    (port->list                 . 端口->列表)
    (filter-read-input-port     . 过滤读取输入端口)
    (dup-input-port             . 复制输入端口)
    (dup-output-port            . 复制输出端口)))

;; ============================================================
;; 关键字翻译表
;; ============================================================
(define 关键字-翻译表
  '((#:exists    . #:如果存在)
    (#:mode      . #:模式)))

;; 关键字值翻译表
(define 关键字值-翻译表
  '((#:exists (截断 . truncate) (替换 . replace) (追加 . append)
              (更新 . update) (可更新 . can-update))
    (#:mode   (文本 . text) (字节 . binary))))

;; ============================================================
;; 2. 构建双向 Hash 表
;; ============================================================
(define 英->中 (make-hash 标识符-翻译表))
(define 中->英
  (let ([h (make-hash)])
    (for ([p (in-list 标识符-翻译表)])
      (hash-set! h (cdr p) (car p)))
    h))

(define 英kw->中kw (make-hash 关键字-翻译表))
(define 中kw->英kw
  (let ([h (make-hash)])
    (for ([p (in-list 关键字-翻译表)])
      (hash-set! h (cdr p) (car p)))
    h))

(define 英kw->值map
  (for/hash ([(kw cn-vals) (in-dict 关键字值-翻译表)])
    (values kw (for/hash ([p (in-list cn-vals)]) (values (cdr p) (car p))))))

(define 中kw->值map
  (for/hash ([(en-kw cn-vals) (in-dict 关键字值-翻译表)])
    (values (dict-ref 英kw->中kw en-kw)
            (for/hash ([p (in-list cn-vals)]) (values (car p) (cdr p))))))

;; ============================================================
;; 3. 核心翻译函数
;; ============================================================

(define (翻译语法 stx #:方向 [方向 '英->中])
  (let* ([id-map (if (eq? 方向 '英->中) 英->中 中->英)]
         [kw-map (if (eq? 方向 '英->中) 英kw->中kw 中kw->英kw)]
         [kw-val-map (if (eq? 方向 '英->中) 英kw->值map 中kw->值map)])
    (let 翻译递归 ([stx stx] [last-kw #f])
      (syntax-case stx ()
[(a . d)
         (let* ([a-is-kw? (keyword? (syntax-e #'a))]
                [next-kw (if a-is-kw? (syntax-e #'a) last-kw)]
                [a-trans (翻译递归 #'a last-kw)]
                [d-trans (翻译递归 #'d next-kw)])
           (datum->syntax stx (cons a-trans d-trans) stx stx))]
        [_
         (let ([val (syntax-e stx)])
           (cond
             [(identifier? stx)
              (let ([found (hash-ref id-map val #f)])
                (if found
                    (datum->syntax stx found stx stx)
                    (if last-kw
                        (let* ([vm (hash-ref kw-val-map last-kw #f)]
                               [vfound (and vm (hash-ref vm val #f))])
                          (if vfound
                              (datum->syntax stx vfound stx stx)
                              stx))
                        stx)))]
             [(keyword? val)
              (let ([found (hash-ref kw-map val #f)])
                (if found
                    (datum->syntax stx found stx stx)
                    stx))]
             [(and last-kw (pair? val)
                   (eq? (car val) 'quote)
                   (pair? (cdr val))
                   (symbol? (cadr val))
                   (null? (cddr val)))
              (let* ([q (cadr val)]
                     [vm (hash-ref kw-val-map last-kw #f)]
                     [found (and vm (hash-ref vm q #f))])
                (if found
                    (datum->syntax stx (list 'quote found) stx stx)
                    stx))]
             [else stx]))]))))

(define (翻译字符串 str #:方向 [方向 '英->中])
  (define in (open-input-string str))
  (define out (open-output-string))
  (let loop ()
    (define stx (read-syntax "translation-input" in))
    (unless (eof-object? stx)
      (define translated (翻译语法 stx #:方向 方向))
      (write (syntax->datum translated) out)
      (newline out)
      (loop)))
  (get-output-string out))

;; ============================================================
;; 4. 文件翻译
;; ============================================================

(define (翻译文件 输入路径 #:输出路径 [输出路径 #f] #:方向 [方向 '英->中])
  (define 方向-名字 (if (eq? 方向 '英->中) "英文→中文" "中文→英文"))
  (define 内容 (file->string 输入路径))
  (define 翻译后
    (cond
      [(string-prefix? 内容 "#lang")
       (let* ([lines (string-split 内容 "\n")]
              [lang-line (first lines)]
              [rest-lines (string-join (rest lines) "\n")])
         (string-append lang-line "\n" (翻译字符串 rest-lines #:方向 方向)))]
      [else (翻译字符串 内容 #:方向 方向)]))
  (if 输出路径
      (begin
        (display-to-file 翻译后 输出路径 #:exists 'replace)
        (printf "✓ 翻译完成 (~a): ~a → ~a\n" 方向-名字 输入路径 输出路径))
      (display 翻译后)))

;; ============================================================
;; 5. 命令行接口
;; ============================================================
(module+ main
  (require racket/match)
  (define args (current-command-line-arguments))
  (define 输入文件 #f)
  (define 输出文件 #f)
  (define 方向 '英->中)
  (let loop ([remaining (vector->list args)])
    (match remaining
      [(list) (void)]
      [(list "--en-to-cn" rest ...) (set! 方向 '英->中) (loop rest)]
      [(list "--en2cn" rest ...)     (set! 方向 '英->中) (loop rest)]
      [(list "--cn-to-en" rest ...) (set! 方向 '中->英) (loop rest)]
      [(list "--cn2en" rest ...)     (set! 方向 '中->英) (loop rest)]
      [(list "-o" path rest ...)     (set! 输出文件 path) (loop rest)]
      [(list "--output" path rest ...) (set! 输出文件 path) (loop rest)]
      [(list f rest ...)
       (if (not (string-prefix? f "-"))
           (begin (set! 输入文件 f) (loop rest))
           (error (format "未知选项: ~a" f)))]))
  (unless 输入文件
    (printf "用法: racket translator.rkt <输入文件> [选项]\n")
    (printf "选项:\n")
    (printf "  --en-to-cn, --en2cn      英文 Racket -> 中文 Racket (默认)\n")
    (printf "  --cn-to-en, --cn2en      中文 Racket -> 英文 Racket\n")
    (printf "  -o, --output <文件>      输出到文件 (省略则输出到终端)\n")
    (exit 1))
  (翻译文件 输入文件 #:输出路径 输出文件 #:方向 方向))
