#lang racket/base
(require racket/mutable-treelist)
(require "../rename-macro.rkt")

(rename-define
  [mutable-treelist 可变树列表]
  [mutable-treelist? 可变树列表?]
  [mutable-treelist-empty? 可变树列表-空?]
  [mutable-treelist-length 可变树列表-长度]
  [mutable-treelist-ref 可变树列表-引用]
  [mutable-treelist-set! 可变树列表-设置!]
  [mutable-treelist-add! 可变树列表-添加!]
  [mutable-treelist-insert! 可变树列表-插入!]
  [mutable-treelist-delete! 可变树列表-删除!]
  [mutable-treelist-append! 可变树列表-拼接!]
  [mutable-treelist-cons! 可变树列表-对!]
  [mutable-treelist-prepend! 可变树列表-前插!]
  [mutable-treelist-first 可变树列表-首]
  [mutable-treelist-last 可变树列表-尾]
  [mutable-treelist-take! 可变树列表-取前!]
  [mutable-treelist-drop! 可变树列表-去掉前!]
  [mutable-treelist-take-right! 可变树列表-取后!]
  [mutable-treelist-drop-right! 可变树列表-去掉后!]
  [mutable-treelist-reverse! 可变树列表-反转!]
  [mutable-treelist-member? 可变树列表-成员?]
  [mutable-treelist-find 可变树列表-查找]
  [mutable-treelist-map! 可变树列表-映射!]
  [mutable-treelist-for-each 可变树列表-遍历]
  [mutable-treelist-sort! 可变树列表-排序!]
  [mutable-treelist-sublist! 可变树列表-子列表!]
  [mutable-treelist-snapshot 可变树列表-快照]
  [mutable-treelist-copy 可变树列表-复制]
  [make-mutable-treelist 制造可变树列表]
  [in-mutable-treelist 在可变树列表]
  [for/mutable-treelist 循环/可变树列表]
  [for*/mutable-treelist 循环*/可变树列表]
)
